version: '3.8'
services:
  stats-client:
    build: stats-service/stats-client
    image: ewm-stats-client
    container_name: stats-client
    ports:
      - "9090:9090"
    environment:
      - stats-client-port=9090
      - stats-server.url=http://stats-server:9093
    depends_on:
      - stats-server

  stats-server:
    build: stats-service/stats-server
    image: ewm-stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      - stats-server-port=9093
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5432/stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    hostname: stats_db

  ewm-service:
    build: main-service
    image: ewm-main-server
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - ewm-server-port=8080
      - stats-server.url=http://stats-client:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_db:5432/ewm
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    hostname: ewm_db